#!/usr/bin/ruby 

if ARGV[0]=='h'
  abort("Usage: #{$0} [optional: <length>] [optional: an (alphanumeric only)]") 
end

# Include special chars?
if ARGV.include?('an')
  # Alphanumeric only
  chars = (48..57).to_a + (65..90).to_a + (97..122).to_a 
else
  chars = (33..126).to_a
end

# Get output length
if ARGV.length >= 1 && ARGV[0] =~ /^\d+$/
  length = ARGV[0].to_i
else
  length = 16
end

output = ''
length.times { output += chars.shuffle.first.chr }

puts output 
